[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
