[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
